# Generated by Django 4.0.4 on 2022-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False, help_text='Select this button to publish this job on the job portal'),
        ),
    ]
