# Generated by Django 4.0.4 on 2022-05-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_post_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False, help_text='Select to publish this job on the job portal page. De-select to hide this job.'),
        ),
    ]
