# Generated by Django 4.0.4 on 2022-05-03 06:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_published',
            new_name='publish',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='Hey'),
            preserve_default=False,
        ),
    ]
