# Generated by Django 4.0.4 on 2022-05-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='resume',
        ),
    ]
