# Generated by Django 4.0.4 on 2022-05-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_post_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reference',
            field=models.CharField(choices=[('website', 'Our Website'), ('employee', 'Eaglehr Employee'), ('social', 'Social Media'), ('internet', 'Internet Search'), ('friend', 'Friend'), ('Newspaper', 'Newspaper')], default='website', max_length=255),
        ),
    ]
