# Generated by Django 4.0.4 on 2022-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.FloatField(blank=True, default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=1, help_text='Number of Days'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
    ]
