# Generated by Django 4.0.4 on 2022-05-17 06:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(default=False, help_text='Display an important message at the very top of the webpage')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Display this event on upcoming events section on homepage. Only the first 4 are displayed.'),
        ),
    ]
