# Generated by Django 4.0.4 on 2022-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_bannermessage_alter_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermessage',
            name='name',
            field=models.CharField(default='Mashujaa', max_length=255),
            preserve_default=False,
        ),
    ]
