# Generated by Django 4.0.4 on 2022-05-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_bannermessage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
