# Generated by Django 4.0.4 on 2022-05-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_event_publish_alter_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='publish',
            new_name='is_active',
        ),
    ]
